@startuml ("Payment API Component")

'skinparam linetype polyline
skinparam nodesep 20
skinparam ranksep 50

component Payment {

    component "TransactionController" as api
    [TransactionProcessingService] as trProc
    together {
        [UserService] as user
        () " " as intUser
    }
    together {
        [OperationService] as op
        () " " as intOp
    }
    together {
        [TransactionService] as tr
        () " " as intTr
    }
    together {
        [AccountService] as acc
        () " " as intAccount
    }
    together {
        [CardService] as card
        () " " as intCard
    }
    together {
        [NotificationService] as not
        () " " as intNot
    }
}
user -l- intUser
card -u- intCard
acc -u- intAccount
not -u- intNot
tr -u- intTr
op -l- intOp

tr --> intOp

api -d-> intTr


trProc --> intNot
trProc -u-> intOp
op -d-> intAccount
op -d-> intCard

user -> Postgres
tr -> Postgres
card -> Postgres
acc -> Postgres
not -> Postgres

database "Postgres" {

}

@enduml