@startuml name topup fail
title withdrawal unsuccess flow
box "Payment Provider" #LightBlue
participant "Transaction processor" as proc
participant "Transaction" as tr
participant "Card" as card
participant "Account" as acc
participant "Notification" as not
end box
database "Postgres" as db
participant "Merchant" as merchant

proc -> tr : get transactions for processing
activate proc
activate tr
tr -> db : query transactions
tr <- db : transactions for processing
tr -> proc : transactions for processing
deactivate tr
proc -> acc: check card balance
activate acc
acc -> db: get balance
db -> acc: result
acc -> proc: insufficient balance
deactivate acc
    proc -> tr: update transaction
    activate tr
    tr->tr: create transaction error
    tr -> db: update transaction and error
    tr <- db: success
    tr -> proc: success
    deactivate tr
proc -> not: send notification
deactivate proc
activate not
deactivate tr
activate not
not -> merchant : send notification
not <- merchant : response
not -> db : save notification result
not <- db : success
deactivate not

@enduml